PAGING_ON_NEXT_PAGE_BTN_CLICK = "PAGING_ON_NEXT_PAGE_BTN_CLICK"
PAGING_ON_PREV_PAGE_BTN_CLICK = "PAGING_ON_PREV_PAGE_BTN_CLICK"

DIALOGS_PREFIX = "DIALOGS_PREFIX"

MESSAGES_PREFIX = "MESSAGES_PREFIX"

SHOW_LOADING_PROGRESS = "SHOW_LOADING_PROGRESS"

DISMISS_LOADING_PROGRESS = "DISMISS_LOADING_PROGRESS"


def get_paging_btn_clicks(prefix: str):
    return (prefix + PAGING_ON_NEXT_PAGE_BTN_CLICK), (prefix + PAGING_ON_PREV_PAGE_BTN_CLICK)

# APP BLUE RGB: 33 150 243
